CREATE TABLE DBADash.AIModels
(
    ModelID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ModelName NVARCHAR(128) NOT NULL,
    DisplayName NVARCHAR(256) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    IsEnabled BIT NOT NULL DEFAULT 1
)
