CREATE TABLE DBADash.Users(
	UserID INT IDENTITY(1,1) CONSTRAINT PK_DBADash_Users PRIMARY KEY,
	UserName NVARCHAR(128) NOT NULL,
	CreatedDate DATETIME2(2) NOT NULL CONSTRAINT DF_DBADash_Users_CreatedDate DEFAULT(SYSUTCDATETIME()),
	TimeZone VARCHAR(50) NULL,
	Theme VARCHAR(50) NULL
)