CREATE TABLE DBADash.XETraceTemplate(
	XETraceTemplateID INT IDENTITY(1,1) CONSTRAINT PK_DBADash_XETraceTemplate PRIMARY KEY,
	UserID INT NOT NULL REFERENCES DBADash.Users(UserID),
	Name NVARCHAR(128) NOT NULL,
	Definition NVARCHAR(MAX) NOT NULL,
	CreatedDate DATETIME2(2) NOT NULL CONSTRAINT DF_DBADash_XETraceTemplate_CreatedDate DEFAULT(SYSUTCDATETIME()),
	ModifiedDate DATETIME2(2) NOT NULL CONSTRAINT DF_DBADash_XETraceTemplate_ModifiedDate DEFAULT(SYSUTCDATETIME())
)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_DBADash_XETraceTemplate_UserID_Name ON DBADash.XETraceTemplate(UserID,Name)
