CREATE TYPE [dbo].[Jobs] AS TABLE (
    [job_id]                  UNIQUEIDENTIFIER NOT NULL,
    [originating_server]      NVARCHAR (128)   NULL,
    [name]                    NVARCHAR (128)   NULL,
    [enabled]                 TINYINT          NULL,
    [description]             NVARCHAR (512)   NULL,
    [start_step_id]           INT              NULL,
    [category_id]             INT              NULL,
    [category]                NVARCHAR (128)   NULL,
    [owner]                   NVARCHAR (128)   NULL,
    [notify_level_eventlog]   INT              NULL,
    [notify_level_email]      INT              NULL,
    [notify_level_netsend]    INT              NULL,
    [notify_level_page]       INT              NULL,
    [notify_email_operator]   NVARCHAR (128)   NULL,
    [notify_netsend_operator] NVARCHAR (128)   NULL,
    [notify_page_operator]    NVARCHAR (128)   NULL,
    [delete_level]            INT              NULL,
    [date_created]            DATETIME         NULL,
    [date_modified]           DATETIME         NULL,
    [version_number]          INT              NULL,
    [has_schedule]            BIT              NULL,
    [has_server]              BIT              NULL,
    [has_step]                BIT              NULL,
    [DDLHash]                 BINARY (32)      NULL,
    [DDL]                     VARBINARY (MAX)  NULL,
    PRIMARY KEY CLUSTERED ([job_id] ASC));

