CREATE TYPE dbo.ResourceGovernorResourcePools AS TABLE(
	SnapshotDate DATETIME2(7) NOT NULL,
	pool_id INT NOT NULL,
	name NVARCHAR(256) NOT NULL,
	statistics_start_time DATETIMEOFFSET(3) NULL,
	total_cpu_usage_ms BIGINT NOT NULL,
	cache_memory_kb BIGINT NOT NULL,
	compile_memory_kb BIGINT NOT NULL,
	used_memgrant_kb BIGINT NOT NULL,
	total_memgrant_count BIGINT NOT NULL,
	total_memgrant_timeout_count BIGINT NOT NULL,
	active_memgrant_count INT NOT NULL,
	active_memgrant_kb BIGINT NOT NULL,
	memgrant_waiter_count INT NOT NULL,
	max_memory_kb BIGINT NOT NULL,
	used_memory_kb BIGINT NOT NULL,
	target_memory_kb BIGINT NOT NULL,
	out_of_memory_count BIGINT NOT NULL,
	min_cpu_percent INT NOT NULL,
	max_cpu_percent INT NOT NULL,
	min_memory_percent INT NOT NULL,
	max_memory_percent INT NOT NULL,
	cap_cpu_percent INT NOT NULL,
	min_iops_per_volume INT NULL,
	max_iops_per_volume INT NULL,
	read_io_queued_total INT NULL,
	read_io_issued_total INT NULL,
	read_io_completed_total INT NOT NULL,
	read_io_throttled_total INT NULL,
	read_bytes_total BIGINT NOT NULL,
	read_io_stall_total_ms BIGINT NOT NULL,
	read_io_stall_queued_ms BIGINT NULL,
	write_io_queued_total INT NULL,
	write_io_issued_total INT NULL,
	write_io_completed_total INT NOT NULL,
	write_io_throttled_total INT NULL,
	write_bytes_total BIGINT NOT NULL,
	write_io_stall_total_ms BIGINT NOT NULL,
	write_io_stall_queued_ms BIGINT NULL,
	io_issue_violations_total INT NULL,
	io_issue_delay_total_ms BIGINT NULL,
	io_issue_delay_non_throttled_total_ms BIGINT NULL,
	total_cpu_delayed_ms BIGINT NOT NULL,
	total_cpu_active_ms BIGINT NOT NULL,
	total_cpu_violation_delay_ms BIGINT NOT NULL,
	total_cpu_violation_sec BIGINT NOT NULL,
	total_cpu_usage_preemptive_ms BIGINT NOT NULL
)
