CREATE TYPE dbo.ResourceGovernorWorkloadGroups AS TABLE(
    SnapshotDate DATETIME2 NOT NULL,
    group_id INT NOT NULL,
    name NVARCHAR(256) NOT NULL,
    pool_id INT NOT NULL,
    pool_name NVARCHAR(256) NOT NULL,  
    external_pool_id INT NULL,
    statistics_start_time DATETIMEOFFSET NOT NULL,
    total_request_count BIGINT NOT NULL,
    total_queued_request_count BIGINT NOT NULL,
    active_request_count INT NOT NULL,
    queued_request_count INT NOT NULL,
    total_cpu_limit_violation_count BIGINT NOT NULL,
    total_cpu_usage_ms BIGINT NOT NULL,
    max_request_cpu_time_ms BIGINT NOT NULL,
    blocked_task_count INT NOT NULL,
    total_lock_wait_count BIGINT NOT NULL,
    total_lock_wait_time_ms BIGINT NOT NULL,
    total_query_optimization_count BIGINT NOT NULL,
    total_suboptimal_plan_generation_count BIGINT NOT NULL,
    total_reduced_memgrant_count BIGINT NOT NULL,
    max_request_grant_memory_kb BIGINT NOT NULL,
    active_parallel_thread_count BIGINT NOT NULL,
    importance NVARCHAR(256) NOT NULL,
    request_max_memory_grant_percent INT NOT NULL,
    request_max_cpu_time_sec INT NOT NULL,
    request_memory_grant_timeout_sec INT NOT NULL,
    group_max_requests INT NOT NULL,
    max_dop INT NOT NULL,
    effective_max_dop INT NULL,
    total_cpu_usage_preemptive_ms BIGINT NULL,
    request_max_memory_grant_percent_numeric FLOAT NULL,
    tempdb_data_space_kb BIGINT NULL,
    peak_tempdb_data_space_kb BIGINT NULL,
    total_tempdb_data_limit_violation_count BIGINT NULL,
    PRIMARY KEY (group_id)
);
GO