

CREATE VIEW [dbo].[InstanceInfo]
AS
SELECT I.InstanceID,
	I.Instance,
    I.MachineName,
	I.ComputerNamePhysicalNetBIOS,
	I.ServerName,
	I.InstanceName,
	I.ActivePowerPlanGUID,
    I.ActivePowerPlan,
    I.ProcessorNameString,
    I.SystemManufacturer,
    I.SystemProductName,
	I.physical_memory_kb,
	I.physical_memory_kb/POWER(1024.0,2) PhysicalMemoryGB,
	CAST(maxmem.value AS BIGINT) BufferPoolMB, 
	CAST(maxmem.value AS BIGINT) / (I.physical_memory_kb/1024.0) PctMemoryAllocatedToBufferPool,
	((I.physical_memory_kb/1024)-CAST(maxmem.value AS BIGINT)) / 1024.0 AS MemoryNotAllocatedToBufferPoolGB,
    I.sql_memory_model,	  
   	CASE I.sql_memory_model WHEN 1 THEN 'CONVENTIONAL' WHEN 2 THEN 'LOCK_PAGES' WHEN 3 THEN 'LARGE_PAGES' ELSE NULL END AS sql_memory_model_desc,
	I.OfflineSchedulers,
    I.affinity_type,
	CASE I.affinity_type WHEN 1 THEN 'MANUAL' WHEN 2 THEN 'AUTO' ELSE NULL END AS affinity_type_desc,
    I.cores_per_socket,
	I.socket_count,
	I.cores_per_socket*I.socket_count AS cpu_core_count,
	I.cpu_count/I.hyperthread_ratio AS physical_cpu_count,
    I.cpu_count,
    I.hyperthread_ratio,
	I.numa_node_count,
    I.softnuma_configuration,
    I.ms_ticks,
	I.ms_ticks/60000 host_up_time_mins,
	DATEADD(s,-I.ms_ticks/1000,os.SnapshotDate) AS host_start_time,
	I.sqlserver_start_time,
    I.os_priority_class,
	CASE I.os_priority_class WHEN 32 THEN 'NORMAL' WHEN 128 THEN 'HIGH' ELSE NULL END AS os_priority_class_desc,
    I.max_workers_count,
    I.scheduler_count,
    I.BuildClrVersion,
	I.LicenseType,
    I.NumLicenses,
    I.ProductBuild,
    I.ProductBuildType,
    I.ProductLevel,
    I.ProductMajorVersion,
    I.ProductUpdateLevel,
    I.ProductUpdateReference,
    I.ProductVersion,
	I.Edition,
    I.EditionID,
    I.EngineEdition,
	I.ResourceLastUpdateDateTime,
    I.ResourceVersion,
    I.Collation,
    I.CollationID,
    I.ComparisonStyle,
	I.LCID,
    I.SqlCharSet,
    I.SqlCharSetName,
    I.SqlSortOrder,
    I.SqlSortOrderName,
    I.FileStreamConfiguredLevel,
    I.FileStreamEffectiveLevel,
    I.FileStreamShareName,
    I.HadrManagerStatus,
    I.InstanceDefaultDataPath,
    I.InstanceDefaultLogPath,
    I.IsAdvancedAnalyticsInstalled,
    I.IsClustered,
    I.IsFullTextInstalled,
    I.IsHadrEnabled,
    I.IsIntegratedSecurityOnly,
    I.IsLocalDB,
    I.IsPolybaseInstalled,
    I.IsXTPSupported,
    I.IsAgentRunning,
    I.InstantFileInitializationEnabled,
    I.AgentHostName
FROM dbo.Instances I
JOIN dbo.SysConfig maxmem ON maxmem.InstanceID = I.InstanceID AND maxmem.configuration_id=1544 
LEFT JOIN dbo.CollectionDates os ON os.InstanceID = I.InstanceID AND os.Reference='OSInfo'