CREATE VIEW dbo.AzureDBResourceStats_Raw
AS
SELECT RS.InstanceID,
		RS.end_time,
		RS.avg_cpu_percent,
		RS.avg_data_io_percent,
		RS.avg_log_write_percent,
		RS.avg_memory_usage_percent,
		RS.xtp_storage_percent,
		RS.max_worker_percent,
		RS.max_session_percent,
		RS.dtu_limit,
		RS.avg_instance_cpu_percent,
		RS.avg_instance_memory_percent,
		RS.cpu_limit,
		RS.replica_role,
		RS.avg_cpu_percent AS max_cpu_percent,
		RS.avg_data_io_percent AS max_data_io_percent,
		RS.avg_log_write_percent AS max_log_write_percent,
		RS.avg_memory_usage_percent AS max_memory_usage_percent,
		RS.xtp_storage_percent AS max_xtp_storage_percent,
		RS.avg_instance_cpu_percent AS max_instance_cpu_percent,
		RS.avg_instance_memory_percent AS max_instance_memory_percent,
		DTU.avg_dtu_percent AS avg_dtu_percent,
		DTU.avg_dtu_percent AS max_dtu_percent,
		DTU.avg_dtu,
		DTU.avg_dtu AS max_dtu,
		CASE WHEN DTU.avg_dtu_percent<10 THEN 1 ELSE 0 END AS DTU10,
		CASE WHEN DTU.avg_dtu_percent>=10 AND DTU.avg_dtu_percent<20 THEN 1 ELSE 0 END AS DTU20,
		CASE WHEN DTU.avg_dtu_percent>=20 AND DTU.avg_dtu_percent<30 THEN 1 ELSE 0 END AS DTU30,
		CASE WHEN DTU.avg_dtu_percent>=30 AND DTU.avg_dtu_percent<40 THEN 1 ELSE 0 END AS DTU40,
		CASE WHEN DTU.avg_dtu_percent>=40 AND DTU.avg_dtu_percent<50 THEN 1 ELSE 0 END AS DTU50,
		CASE WHEN DTU.avg_dtu_percent>=50 AND DTU.avg_dtu_percent<60 THEN 1 ELSE 0 END AS DTU60,
		CASE WHEN DTU.avg_dtu_percent>=60 AND DTU.avg_dtu_percent<70 THEN 1 ELSE 0 END AS DTU70,
		CASE WHEN DTU.avg_dtu_percent>=70 AND DTU.avg_dtu_percent<80 THEN 1 ELSE 0 END AS DTU80,
		CASE WHEN DTU.avg_dtu_percent>=80 AND DTU.avg_dtu_percent<90 THEN 1 ELSE 0 END AS DTU90,
		CASE WHEN DTU.avg_dtu_percent>= 90 THEN 1 ELSE 0 END AS DTU100,
		CASE WHEN RS.avg_cpu_percent <10 THEN 1 ELSE 0 END AS CPU10,
		CASE WHEN RS.avg_cpu_percent >=10 AND RS.avg_cpu_percent <20 THEN 1 ELSE 0 END AS CPU20,
		CASE WHEN RS.avg_cpu_percent >=20 AND RS.avg_cpu_percent <30 THEN 1 ELSE 0 END AS CPU30,
		CASE WHEN RS.avg_cpu_percent >=30 AND RS.avg_cpu_percent <40 THEN 1 ELSE 0 END AS CPU40,
		CASE WHEN RS.avg_cpu_percent >=40 AND RS.avg_cpu_percent <50 THEN 1 ELSE 0 END AS CPU50,
		CASE WHEN RS.avg_cpu_percent >=50 AND RS.avg_cpu_percent <60 THEN 1 ELSE 0 END AS CPU60,
		CASE WHEN RS.avg_cpu_percent >=60 AND RS.avg_cpu_percent <70 THEN 1 ELSE 0 END AS CPU70,
		CASE WHEN RS.avg_cpu_percent >=70 AND RS.avg_cpu_percent <80 THEN 1 ELSE 0 END AS CPU80,
		CASE WHEN RS.avg_cpu_percent >=80 AND RS.avg_cpu_percent <90 THEN 1 ELSE 0 END AS CPU90,
		CASE WHEN RS.avg_cpu_percent >= 90 THEN 1 ELSE 0 END AS CPU100,
		CASE WHEN RS.avg_data_io_percent <10 THEN 1 ELSE 0 END AS Data10,
		CASE WHEN RS.avg_data_io_percent>=10 AND RS.avg_data_io_percent<20 THEN 1 ELSE 0 END AS Data20,
		CASE WHEN RS.avg_data_io_percent>=20 AND RS.avg_data_io_percent<30 THEN 1 ELSE 0 END AS Data30,
		CASE WHEN RS.avg_data_io_percent>=30 AND RS.avg_data_io_percent<40 THEN 1 ELSE 0 END AS Data40,
		CASE WHEN RS.avg_data_io_percent>=40 AND RS.avg_data_io_percent<50 THEN 1 ELSE 0 END AS Data50,
		CASE WHEN RS.avg_data_io_percent>=50 AND RS.avg_data_io_percent<60 THEN 1 ELSE 0 END AS Data60,
		CASE WHEN RS.avg_data_io_percent>=60 AND RS.avg_data_io_percent<70 THEN 1 ELSE 0 END AS Data70,
		CASE WHEN RS.avg_data_io_percent>=70 AND RS.avg_data_io_percent<80 THEN 1 ELSE 0 END AS Data80,
		CASE WHEN RS.avg_data_io_percent>=80 AND RS.avg_data_io_percent<90 THEN 1 ELSE 0 END AS Data90,
		CASE WHEN RS.avg_data_io_percent>= 90 THEN 1 ELSE 0 END AS Data100,
		CASE WHEN RS.avg_log_write_percent <10 THEN 1 ELSE 0 END AS Log10,
		CASE WHEN RS.avg_log_write_percent >=10 AND RS.avg_log_write_percent <20 THEN 1 ELSE 0 END AS Log20,
		CASE WHEN RS.avg_log_write_percent >=20 AND RS.avg_log_write_percent <30 THEN 1 ELSE 0 END AS Log30,
		CASE WHEN RS.avg_log_write_percent >=30 AND RS.avg_log_write_percent <40 THEN 1 ELSE 0 END AS Log40,
		CASE WHEN RS.avg_log_write_percent >=40 AND RS.avg_log_write_percent <50 THEN 1 ELSE 0 END AS Log50,
		CASE WHEN RS.avg_log_write_percent >=50 AND RS.avg_log_write_percent <60 THEN 1 ELSE 0 END AS Log60,
		CASE WHEN RS.avg_log_write_percent >=60 AND RS.avg_log_write_percent <70 THEN 1 ELSE 0 END AS Log70,
		CASE WHEN RS.avg_log_write_percent >=70 AND RS.avg_log_write_percent <80 THEN 1 ELSE 0 END AS Log80,
		CASE WHEN RS.avg_log_write_percent >=80 AND RS.avg_log_write_percent <90 THEN 1 ELSE 0 END AS Log90,
		CASE WHEN RS.avg_log_write_percent >= 90 THEN 1 ELSE 0 END AS Log100
FROM dbo.AzureDBResourceStats RS
CROSS APPLY dbo.DateGroupingMins(RS.end_time,60) DG
OUTER APPLY(SELECT 	CASE WHEN dtu_limit>0 THEN (SELECT Max(value.v) FROM (VALUES (avg_cpu_percent), (avg_data_io_percent), (avg_log_write_percent)) AS value(v)) ELSE NULL END AS [avg_dtu_percent],
					CASE WHEN dtu_limit>0 THEN ((dtu_limit)*((SELECT Max(value.v) FROM (VALUES (avg_cpu_percent), (avg_data_io_percent), (avg_log_write_percent)) AS value(v))/100.00)) ELSE NULL END AS [avg_dtu]
			) AS DTU