CREATE VIEW dbo.FilegroupStatus
AS
SELECT NULL AS FileID,
	   F.InstanceID,
       F.DatabaseID,
       F.data_space_id,
       F.Instance,
       F.InstanceDisplayName,
       F.InstanceGroupName,
       F.ConnectionID,
       F.name,
       NULL AS file_name,
       F.filegroup_name,
       NULL AS physical_name,
       F.FilegroupSizeMB AS FileSizeMB,
       F.FilegroupUsedMB AS FileUsedMB,
       F.FilegroupFreeMB AS FileFreeMB,
       F.FilegroupPctFree AS FilePctFree,
       F.FilegroupSizeMB,
       F.FilegroupUsedMB,
       F.FilegroupFreeMB,
       F.FilegroupPctFree,
       F.FilegroupNumberOfFiles,
       F.is_read_only,
       F.is_db_read_only,
       F.is_in_standby,
       F.state,
       F.state_desc,
       F.ExcludedReason,
       F.FreeSpaceStatus,
       F.FreeSpaceWarningThreshold,
       F.FreeSpaceCriticalThreshold,
       F.FreeSpaceCheckType,
       F.ConfiguredLevel,
       F.FileSnapshotDate,
       F.FileSnapshotAge,
	   F.FileSnapshotAgeStatus,
	   F.FilegroupMaxSizeMB,
	   F.FilegroupPctOfMaxSize,
	   F.FilegroupUsedPctOfMaxSize,
	   F.PctMaxSizeStatus,
	   F.MaxSizeExcludedReason,
	   F.FilegroupAutogrowFileCount,
	   F.FilegroupAutogrowStatus,
       F.type,
       F.type_desc,
       F.ShowInSummary
FROM dbo.FileStatus F 
GROUP BY  F.InstanceID,
       F.DatabaseID,
       F.data_space_id,
       F.Instance,
       F.InstanceDisplayName,
       F.InstanceGroupName,
       F.ConnectionID,
       F.name,
       F.filegroup_name,
       F.FilegroupSizeMB,
       F.FilegroupUsedMB,
       F.FilegroupFreeMB,
       F.FilegroupPctFree,
       F.FilegroupNumberOfFiles,
       F.is_read_only,
       F.is_db_read_only,
       F.is_in_standby,
       F.state,
       F.state_desc,
       F.ExcludedReason,
       F.FreeSpaceStatus,
       F.FreeSpaceWarningThreshold,
       F.FreeSpaceCriticalThreshold,
       F.FreeSpaceCheckType,
       F.ConfiguredLevel,
       F.FileSnapshotDate,
       F.FileSnapshotAge,
	   F.FileSnapshotAgeStatus,
	   F.FilegroupMaxSizeMB,
	   F.FilegroupPctOfMaxSize,
	   F.FilegroupUsedPctOfMaxSize,
	   F.PctMaxSizeStatus,
	   F.MaxSizeExcludedReason,
	   F.FilegroupAutogrowFileCount,
	   F.FilegroupAutogrowStatus,
       F.type,
       F.type_desc,
       F.ShowInSummary