CREATE TABLE [Switch].[AzureDBElasticPoolResourceStats_60MIN] (
    [PoolID]                        INT            NOT NULL,
    [end_time]                      DATETIME2 (3)  NOT NULL,
    [avg_cpu_percent]               DECIMAL (5, 2) NOT NULL,
    [max_cpu_percent]               DECIMAL (5, 2) NOT NULL,
    [avg_data_io_percent]           DECIMAL (5, 2) NOT NULL,
    [max_data_io_percent]           DECIMAL (5, 2) NOT NULL,
    [avg_log_write_percent]         DECIMAL (5, 2) NOT NULL,
    [max_log_write_percent]         DECIMAL (5, 2) NOT NULL,
    [avg_storage_percent]           DECIMAL (5, 2) NOT NULL,
    [max_storage_percent]           DECIMAL (5, 2) NOT NULL,
    [max_worker_percent]            DECIMAL (5, 2) NOT NULL,
    [max_session_percent]           DECIMAL (5, 2) NOT NULL,
    [elastic_pool_dtu_limit]        INT            NULL,
    [elastic_pool_cpu_limit]        INT            NULL,
    [elastic_pool_storage_limit_mb] BIGINT         NULL,
    [avg_allocated_storage_percent] DECIMAL (5, 2) NULL,
    [avg_dtu_percent]               DECIMAL (5, 2) NULL,
    [max_dtu_percent]               DECIMAL (5, 2) NULL,
    [avg_dtu]                       DECIMAL (9, 2) NULL,
    [max_dtu]                       DECIMAL (9, 2) NULL,
    [DTU10]                         SMALLINT       NOT NULL,
    [DTU20]                         SMALLINT       NOT NULL,
    [DTU30]                         SMALLINT       NOT NULL,
    [DTU40]                         SMALLINT       NOT NULL,
    [DTU50]                         SMALLINT       NOT NULL,
    [DTU60]                         SMALLINT       NOT NULL,
    [DTU70]                         SMALLINT       NOT NULL,
    [DTU80]                         SMALLINT       NOT NULL,
    [DTU90]                         SMALLINT       NOT NULL,
    [DTU100]                        SMALLINT       NOT NULL,
    [CPU10]                         SMALLINT       NOT NULL,
    [CPU20]                         SMALLINT       NOT NULL,
    [CPU30]                         SMALLINT       NOT NULL,
    [CPU40]                         SMALLINT       NOT NULL,
    [CPU50]                         SMALLINT       NOT NULL,
    [CPU60]                         SMALLINT       NOT NULL,
    [CPU70]                         SMALLINT       NOT NULL,
    [CPU80]                         SMALLINT       NOT NULL,
    [CPU90]                         SMALLINT       NOT NULL,
    [CPU100]                        SMALLINT       NOT NULL,
    [Data10]                        SMALLINT       NOT NULL,
    [Data20]                        SMALLINT       NOT NULL,
    [Data30]                        SMALLINT       NOT NULL,
    [Data40]                        SMALLINT       NOT NULL,
    [Data50]                        SMALLINT       NOT NULL,
    [Data60]                        SMALLINT       NOT NULL,
    [Data70]                        SMALLINT       NOT NULL,
    [Data80]                        SMALLINT       NOT NULL,
    [Data90]                        SMALLINT       NOT NULL,
    [Data100]                       SMALLINT       NOT NULL,
    [Log10]                         SMALLINT       NOT NULL,
    [Log20]                         SMALLINT       NOT NULL,
    [Log30]                         SMALLINT       NOT NULL,
    [Log40]                         SMALLINT       NOT NULL,
    [Log50]                         SMALLINT       NOT NULL,
    [Log60]                         SMALLINT       NOT NULL,
    [Log70]                         SMALLINT       NOT NULL,
    [Log80]                         SMALLINT       NOT NULL,
    [Log90]                         SMALLINT       NOT NULL,
    [Log100]                        SMALLINT       NOT NULL,
    CONSTRAINT [PK_AzureDBElasticPoolResourceStats_60MIN] PRIMARY KEY CLUSTERED ([PoolID] ASC, [end_time] ASC) WITH (DATA_COMPRESSION = PAGE)
);

