CREATE TABLE [dbo].[DDL] (
    [DDLID]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [DDLHash] VARBINARY (256) NOT NULL,
    [DDL]     VARBINARY (MAX) NULL,
    PRIMARY KEY CLUSTERED ([DDLID] ASC)
);

