CREATE PROC dbo.BackupSummary_Get(
	@InstanceIDs IDs READONLY
)
AS
SELECT InstanceID,
       Instance,
       InstanceDisplayName,
       DatabaseCount,
       FullRecoveryCount,
       BulkLoggedCount,
       SimpleCount,
       FullOK,
       FullNA,
       FullWarning,
       FullCritical,
       DiffOK,
       DiffNA,
       DiffWarning,
       DiffCritical,
       LogOK,
       LogNA,
       LogWarning,
       LogCritical,
       SnapshotDate,
       SnapshotAge,
       SnapshotAgeStatus,
       FullBackupSizeGB,
       FullBackupMBsec,
       FullBackupSizeCompressedGB,
       FullCompressionSavingPct,
       FullBackupWriteMBsec,
       DiffBackupSizeGB,
       DiffBackupMBsec,
       DiffBackupSizeCompressedGB,
       DiffCompressionSavingPct,
       DiffBackupWriteMBsec,
       FullEncrypted,
       DiffEncrypted,
       LogEncrypted,
       FullChecksum,
       DiffChecksum,
       LogChecksum,
       FullCompressed,
       DiffCompressed,
       LogCompressed,
       FullPasswordProtected,
       DiffPasswordProtected,
       LogPasswordProtected,
       SnapshotBackups,
       DBThresholdConfiguration,
       InstanceThresholdConfiguration,
       IsPartnerBackup,
       OldestFull,
       OldestDiff,
       OldestLog
FROM dbo.BackupSummary B
WHERE EXISTS(SELECT 1 
			FROM @InstanceIDs T 
			WHERE T.ID = B.InstanceID)
ORDER BY Instance