CREATE PROC dbo.ResourceGovernorResourcePools_Upd(
	@ResourceGovernorResourcePools dbo.ResourceGovernorResourcePools READONLY,
	@InstanceID INT,
	@SnapshotDate DATETIME2(2)
)
AS
/*
	Note: matching is done on name rather than pool_id. The pool_id could change if the resource pool is dropped and recreated or if the instance associated with the ConnectionID changes (migrations, failover etc).
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @Ref VARCHAR(30) = 'ResourceGovernorResourcePools';

IF NOT EXISTS (
	SELECT 1
	FROM dbo.CollectionDates
	WHERE SnapshotDate >= CAST(@SnapshotDate AS DATETIME2(2))
	  AND InstanceID = @InstanceID
	  AND Reference = @Ref
)
BEGIN
	/* Insert new records into the Metrics table based on the difference between the current snapshot and the previous snapshot. */
	INSERT INTO dbo.ResourceGovernorResourcePoolsMetrics (
			InstanceID,
			ResourcePoolID,
			SnapshotDate,
			PeriodTimeMs,
			diff_cpu_usage_ms,
			diff_memgrant_count,
			diff_memgrant_timeout_count,
			diff_out_of_memory_count,
			diff_read_io_queued,
			diff_read_io_issued,
			diff_read_io_completed,
			diff_read_io_throttled,
			diff_read_bytes,
			diff_read_io_stall_ms,
			diff_read_io_stall_queued_ms,
			diff_write_io_queued,
			diff_write_io_issued,
			diff_write_io_completed,
			diff_write_io_throttled,
			diff_write_bytes,
			diff_write_io_stall_ms,
			diff_write_io_stall_queued_ms,
			diff_io_issue_violations,
			diff_io_issue_delay_ms,
			diff_io_issue_delay_non_throttled_ms,
			diff_cpu_delayed_ms,
			diff_cpu_active_ms,
			diff_cpu_violation_delay_ms,
			diff_cpu_violation_sec,
			diff_cpu_usage_preemptive_ms,
			cache_memory_kb,
			compile_memory_kb,
			used_memgrant_kb,	
			active_memgrant_count,
			active_memgrant_kb,
			memgrant_waiter_count,
			max_memory_kb,
			used_memory_kb,
			target_memory_kb,
			cpu_count,
			max_cpu_percent,
			cap_cpu_percent
	)
	SELECT	@InstanceID,
			RP.ResourcePoolID,
			T.SnapshotDate,
			DATEDIFF_BIG(ms,RP.SnapshotDate,T.SnapshotDate) AS PeriodTimeMs,
			T.total_cpu_usage_ms - RP.total_cpu_usage_ms AS diff_cpu_usage_ms,
			T.total_memgrant_count - RP.total_memgrant_count AS  diff_memgrant_count,
			T.total_memgrant_timeout_count - RP.total_memgrant_timeout_count AS  diff_memgrant_timeout_count,
			T.out_of_memory_count - RP.out_of_memory_count AS diff_out_of_memory_count,
			T.read_io_queued_total - RP.read_io_queued_total AS diff_read_io_queued,
			T.read_io_issued_total - RP.read_io_issued_total AS diff_read_io_issued,
			T.read_io_completed_total - RP.read_io_completed_total AS diff_read_io_completed,
			T.read_io_throttled_total - RP.read_io_throttled_total AS diff_read_io_throttled,
			T.read_bytes_total - RP.read_bytes_total AS diff_read_bytes,
			T.read_io_stall_total_ms - RP.read_io_stall_total_ms AS diff_read_io_stall_ms,
			T.read_io_stall_queued_ms - RP.read_io_stall_queued_ms AS diff_read_io_stall_queued_ms,
			T.write_io_queued_total - RP.write_io_queued_total AS diff_write_io_queued,
			T.write_io_issued_total - RP.write_io_issued_total AS diff_write_io_issued,
			T.write_io_completed_total - RP.write_io_completed_total AS diff_write_io_completed,
			T.write_io_throttled_total - RP.write_io_throttled_total AS diff_write_io_throttled,
			T.write_bytes_total - RP.write_bytes_total AS diff_write_bytes,
			T.write_io_stall_total_ms - RP.write_io_stall_total_ms AS diff_write_io_stall_ms,
			T.write_io_stall_queued_ms - RP.write_io_stall_queued_ms AS diff_write_io_stall_queued_ms,
			T.io_issue_violations_total - RP.io_issue_violations_total AS diff_io_issue_violations,
			T.io_issue_delay_total_ms - RP.io_issue_delay_total_ms AS diff_io_issue_delay_ms,
			T.io_issue_delay_non_throttled_total_ms - RP.io_issue_delay_non_throttled_total_ms AS diff_io_issue_delay_non_throttled_ms,
			T.total_cpu_delayed_ms - RP.total_cpu_delayed_ms AS diff_cpu_delayed_ms,
			T.total_cpu_active_ms - RP.total_cpu_active_ms AS diff_cpu_active_ms,
			T.total_cpu_violation_delay_ms - RP.total_cpu_violation_delay_ms AS diff_cpu_violation_delay_ms,
			T.total_cpu_violation_sec - RP.total_cpu_violation_sec AS diff_cpu_violation_sec,
			T.total_cpu_usage_preemptive_ms - RP.total_cpu_usage_preemptive_ms AS diff_cpu_usage_preemptive_ms,
			T.cache_memory_kb,
			T.compile_memory_kb,
			T.used_memgrant_kb,	
			T.active_memgrant_count,
			T.active_memgrant_kb,
			T.memgrant_waiter_count,
			T.max_memory_kb,
			T.used_memory_kb,
			T.target_memory_kb,
			I.cpu_count,
			T.max_cpu_percent,
			T.cap_cpu_percent
	FROM dbo.ResourceGovernorResourcePools RP
	JOIN @ResourceGovernorResourcePools T ON RP.name = T.name
	JOIN dbo.Instances I ON RP.InstanceID = I.InstanceID
	WHERE DATEDIFF_BIG(ms, RP.SnapshotDate, T.SnapshotDate) BETWEEN 0 AND 14400000 /* 4 hours in ms.  Skip recording if the gap between collections is too large. */
	AND RP.InstanceID = @InstanceID
	AND RP.statistics_start_time = T.statistics_start_time;

	/* Update the current snapshot in the main table. */
	UPDATE RP
	SET		RP.SnapshotDate  = T.SnapshotDate,
			RP.pool_id = T.pool_id,
			RP.name = T.name,
			RP.statistics_start_time = T.statistics_start_time,
			RP.total_cpu_usage_ms = T.total_cpu_usage_ms,
			RP.cache_memory_kb = T.cache_memory_kb,
			RP.compile_memory_kb = T.compile_memory_kb,
			RP.used_memgrant_kb = T.used_memgrant_kb,
			RP.total_memgrant_count = T.total_memgrant_count,
			RP.total_memgrant_timeout_count = T.total_memgrant_timeout_count,
			RP.active_memgrant_count = T.active_memgrant_count,
			RP.active_memgrant_kb = T.active_memgrant_kb,
			RP.memgrant_waiter_count = T.memgrant_waiter_count,
			RP.max_memory_kb = T.max_memory_kb,
			RP.used_memory_kb = T.used_memory_kb,
			RP.target_memory_kb = T.target_memory_kb,
			RP.out_of_memory_count = T.out_of_memory_count,
			RP.min_cpu_percent = T.min_cpu_percent,
			RP.max_cpu_percent = T.max_cpu_percent,
			RP.min_memory_percent = T.min_memory_percent,
			RP.max_memory_percent = T.max_memory_percent,
			RP.cap_cpu_percent = T.cap_cpu_percent,
			RP.min_iops_per_volume = T.min_iops_per_volume,
			RP.max_iops_per_volume = T.max_iops_per_volume,
			RP.read_io_queued_total = T.read_io_queued_total,
			RP.read_io_issued_total = T.read_io_issued_total,
			RP.read_io_completed_total = T.read_io_completed_total,
			RP.read_io_throttled_total = T.read_io_throttled_total,
			RP.read_bytes_total = T.read_bytes_total,
			RP.read_io_stall_total_ms = T.read_io_stall_total_ms,
			RP.read_io_stall_queued_ms = T.read_io_stall_queued_ms,
			RP.write_io_queued_total = T.write_io_queued_total,
			RP.write_io_issued_total = T.write_io_issued_total,
			RP.write_io_completed_total = T.write_io_completed_total,
			RP.write_io_throttled_total = T.write_io_throttled_total,
			RP.write_bytes_total = T.write_bytes_total,
			RP.write_io_stall_total_ms = T.write_io_stall_total_ms,
			RP.write_io_stall_queued_ms = T.write_io_stall_queued_ms,
			RP.io_issue_violations_total = T.io_issue_violations_total,
			RP.io_issue_delay_total_ms = T.io_issue_delay_total_ms,
			RP.io_issue_delay_non_throttled_total_ms = T.io_issue_delay_non_throttled_total_ms,
			RP.total_cpu_delayed_ms = T.total_cpu_delayed_ms,
			RP.total_cpu_active_ms = T.total_cpu_active_ms,
			RP.total_cpu_violation_delay_ms = T.total_cpu_violation_delay_ms,
			RP.total_cpu_violation_sec = T.total_cpu_violation_sec,
			RP.total_cpu_usage_preemptive_ms = T.total_cpu_usage_preemptive_ms
	FROM dbo.ResourceGovernorResourcePools RP
	JOIN @ResourceGovernorResourcePools T ON RP.name = T.name AND RP.InstanceID = @InstanceID;

	/* Insert new records for any resource pools that don't have a match in the main table. */
	INSERT INTO dbo.ResourceGovernorResourcePools (
			InstanceID,
			SnapshotDate,
			pool_id,
			name,
			statistics_start_time,
			total_cpu_usage_ms,
			cache_memory_kb,
			compile_memory_kb,
			used_memgrant_kb,
			total_memgrant_count,
			total_memgrant_timeout_count,
			active_memgrant_count,
			active_memgrant_kb,
			memgrant_waiter_count,
			max_memory_kb,
			used_memory_kb,
			target_memory_kb,
			out_of_memory_count,
			min_cpu_percent,
			max_cpu_percent,
			min_memory_percent,
			max_memory_percent,
			cap_cpu_percent,
			min_iops_per_volume,
			max_iops_per_volume,
			read_io_queued_total,
			read_io_issued_total,
			read_io_completed_total,
			read_io_throttled_total,
			read_bytes_total,
			read_io_stall_total_ms,
			read_io_stall_queued_ms,
			write_io_queued_total,
			write_io_issued_total,
			write_io_completed_total,
			write_io_throttled_total,
			write_bytes_total,
			write_io_stall_total_ms,
			write_io_stall_queued_ms,
			io_issue_violations_total,
			io_issue_delay_total_ms,
			io_issue_delay_non_throttled_total_ms,
			total_cpu_delayed_ms,
			total_cpu_active_ms,
			total_cpu_violation_delay_ms,
			total_cpu_violation_sec,
			total_cpu_usage_preemptive_ms
	)
	SELECT	@InstanceID,
			SnapshotDate,
			pool_id,
			name,
			statistics_start_time,
			total_cpu_usage_ms,
			cache_memory_kb,
			compile_memory_kb,
			used_memgrant_kb,
			total_memgrant_count,
			total_memgrant_timeout_count,
			active_memgrant_count,
			active_memgrant_kb,
			memgrant_waiter_count,
			max_memory_kb,
			used_memory_kb,
			target_memory_kb,
			out_of_memory_count,
			min_cpu_percent,
			max_cpu_percent,
			min_memory_percent,
			max_memory_percent,
			cap_cpu_percent,
			min_iops_per_volume,
			max_iops_per_volume,
			read_io_queued_total,
			read_io_issued_total,
			read_io_completed_total,
			read_io_throttled_total,
			read_bytes_total,
			read_io_stall_total_ms,
			read_io_stall_queued_ms,
			write_io_queued_total,
			write_io_issued_total,
			write_io_completed_total,
			write_io_throttled_total,
			write_bytes_total,
			write_io_stall_total_ms,
			write_io_stall_queued_ms,
			io_issue_violations_total,
			io_issue_delay_total_ms,
			io_issue_delay_non_throttled_total_ms,
			total_cpu_delayed_ms,
			total_cpu_active_ms,
			total_cpu_violation_delay_ms,
			total_cpu_violation_sec,
			total_cpu_usage_preemptive_ms
	FROM @ResourceGovernorResourcePools T
	WHERE NOT EXISTS (
		SELECT 1
		FROM dbo.ResourceGovernorResourcePools RP
		WHERE RP.name = T.name
		  AND RP.InstanceID = @InstanceID
	);

	EXEC dbo.CollectionDates_Upd @InstanceID = @InstanceID,
							   @Reference = @Ref,
							   @SnapshotDate = @SnapshotDate;
END;
