CREATE PROC dbo.ResourceGovernorResourcePools_Get(
    @InstanceID INT,
    @FromDate  DATETIME,
    @ToDate    DATETIME
)
AS
WITH Metrics AS (
	SELECT  M.ResourcePoolID,
			SUM(M.diff_cpu_usage_ms*1.0) AS period_cpu_usage_ms,
			SUM(M.diff_cpu_usage_ms*1.0)/SUM(M.PeriodTimeMs) AS period_cpu_cores,
			SUM(M.diff_cpu_usage_ms*1.0/M.cpu_count)/SUM(M.PeriodTimeMs) AS period_cpu_percent,
			SUM(M.diff_cpu_usage_ms*1.0)/SUM(SUM(M.diff_cpu_usage_ms)) OVER() AS period_cpu_share_percent,      
			(SUM(M.diff_cpu_usage_ms*1.0/M.cpu_count)/SUM(M.PeriodTimeMs)) * 100.0 / NULLIF(MAX(M.cap_cpu_percent),0) AS cpu_cap_utilization_percent,
			-- Percentage of time CPU usage was at or above 95% of the cap (throttling indicator)
			SUM(CASE 
				WHEN (M.diff_cpu_usage_ms*1.0/M.cpu_count)/M.PeriodTimeMs * 100.0 >= (M.cap_cpu_percent * 0.95) 
				THEN M.PeriodTimeMs 
				ELSE 0 
			END) / NULLIF(SUM(M.PeriodTimeMs)*1.0, 0) AS cpu_cap_near_threshold_percent,
			SUM(M.diff_memgrant_count)/SUM(M.PeriodTimeMs/60000.0) AS period_memgrant_count_per_min,
			SUM(M.diff_memgrant_timeout_count)/SUM(M.PeriodTimeMs/60000.0) AS period_memgrant_timeout_count_per_min,
			SUM(M.diff_out_of_memory_count)/SUM(M.PeriodTimeMs/60000.0) AS period_out_of_memory_count_per_min,
			SUM(M.diff_read_io_queued)/SUM(M.PeriodTimeMs/60000.0) AS period_read_io_queued_per_min,
			SUM(M.diff_read_io_issued)/SUM(M.PeriodTimeMs/60000.0) AS period_read_io_issued_per_min,
			SUM(M.diff_read_io_completed)/SUM(M.PeriodTimeMs/60000.0) AS period_read_io_completed_per_min,
			SUM(M.diff_read_io_throttled)/SUM(M.PeriodTimeMs/60000.0) AS period_read_io_throttled_per_min,
			SUM(M.diff_read_bytes/POWER(1024.0,2))/SUM(M.PeriodTimeMs/1000.0) AS period_read_mb_per_sec,
			SUM(M.diff_read_io_stall_ms)/SUM(M.PeriodTimeMs/60000.0) AS period_read_io_stall_ms_per_min,
			SUM(M.diff_read_io_stall_queued_ms)/SUM(M.PeriodTimeMs/60000.0) AS period_read_io_stall_queued_ms_per_min,
			SUM(M.diff_write_io_queued)/SUM(M.PeriodTimeMs/60000.0) AS period_write_io_queued_per_min,
			SUM(M.diff_write_io_issued)/SUM(M.PeriodTimeMs/60000.0) AS period_write_io_issued_per_min,
			SUM(M.diff_write_io_completed)/SUM(M.PeriodTimeMs/60000.0) AS period_write_io_completed_per_min,
			SUM(M.diff_write_io_throttled)/SUM(M.PeriodTimeMs/60000.0) AS period_write_io_throttled_per_min,
			SUM(M.diff_write_bytes/POWER(1024.0,2))/SUM(M.PeriodTimeMs/1000.0) AS period_write_mb_per_sec,
			SUM(M.diff_write_io_stall_ms)/SUM(M.PeriodTimeMs/60000.0) AS period_write_io_stall_ms_per_min,
			SUM(M.diff_write_io_stall_queued_ms)/SUM(M.PeriodTimeMs/60000.0) AS period_write_io_stall_queued_ms_per_min,
			SUM(M.diff_io_issue_delay_ms)/SUM(M.PeriodTimeMs/60000.0) AS period_io_issue_delay_ms_per_min,
			SUM(M.diff_io_issue_delay_non_throttled_ms)/SUM(M.PeriodTimeMs/60000.0) AS period_io_issue_delay_non_throttled_ms_per_min,
			SUM(M.diff_cpu_delayed_ms)/SUM(M.PeriodTimeMs/60000.0) AS period_cpu_delayed_ms_per_min,
			SUM(M.diff_cpu_active_ms)/SUM(M.PeriodTimeMs/60000.0) AS period_cpu_active_ms_per_min,
			SUM(M.diff_cpu_violation_delay_ms)/SUM(M.PeriodTimeMs/60000.0) AS period_cpu_violation_delay_ms_per_min,
			SUM(M.diff_cpu_violation_sec)/SUM(M.PeriodTimeMs/60000.0) AS period_cpu_violation_sec_per_min,
			SUM(M.diff_cpu_usage_preemptive_ms)/SUM(M.PeriodTimeMs/60000.0) AS period_cpu_usage_preemptive_ms_per_min
	FROM dbo.ResourceGovernorResourcePoolsMetrics M
	WHERE M.InstanceID = @InstanceID
	AND M.SnapshotDate >= @FromDate
	AND M.SnapshotDate < @ToDate
	GROUP BY M.ResourcePoolID
)
SELECT  RP.ResourcePoolID,
        RP.InstanceID,
        RP.SnapshotDate,
        RP.pool_id,
        RP.name,
        M.period_cpu_usage_ms,
        M.period_cpu_cores,
        M.period_cpu_percent,
        M.period_cpu_share_percent,
        M.cpu_cap_near_threshold_percent,
        M.period_memgrant_count_per_min,
        M.period_memgrant_timeout_count_per_min,
        M.period_out_of_memory_count_per_min,
        M.period_read_io_queued_per_min,
        M.period_read_io_issued_per_min,
        M.period_read_io_completed_per_min,
        M.period_read_io_throttled_per_min,
        M.period_read_mb_per_sec,
        M.period_read_io_stall_ms_per_min,
        M.period_read_io_stall_queued_ms_per_min,
        M.period_write_io_queued_per_min,
        M.period_write_io_issued_per_min,
        M.period_write_io_completed_per_min,
        M.period_write_io_throttled_per_min,
        M.period_write_mb_per_sec,
        M.period_write_io_stall_ms_per_min,
        M.period_write_io_stall_queued_ms_per_min,
        M.period_io_issue_delay_ms_per_min,
        M.period_io_issue_delay_non_throttled_ms_per_min,
        M.period_cpu_delayed_ms_per_min,
        M.period_cpu_active_ms_per_min,
        M.period_cpu_violation_delay_ms_per_min,
        M.period_cpu_violation_sec_per_min,
        M.period_cpu_usage_preemptive_ms_per_min,
        RP.statistics_start_time,
        RP.total_cpu_usage_ms,
        RP.cache_memory_kb,
        RP.compile_memory_kb,
        RP.used_memgrant_kb,
        RP.total_memgrant_count,
        RP.total_memgrant_timeout_count,
        RP.active_memgrant_count,
        RP.active_memgrant_kb,
        RP.memgrant_waiter_count,
        RP.max_memory_kb,
        RP.used_memory_kb,
        RP.target_memory_kb,
        RP.out_of_memory_count,
        RP.min_cpu_percent,
        RP.max_cpu_percent,
        RP.min_memory_percent,
        RP.max_memory_percent,
        RP.cap_cpu_percent,
        RP.min_iops_per_volume,
        RP.max_iops_per_volume,
        RP.read_io_queued_total,
        RP.read_io_issued_total,
        RP.read_io_completed_total,
        RP.read_io_throttled_total,
        RP.read_bytes_total,
        RP.read_io_stall_total_ms,
        RP.read_io_stall_queued_ms,
        RP.write_io_queued_total,
        RP.write_io_issued_total,
        RP.write_io_completed_total,
        RP.write_io_throttled_total,
        RP.write_bytes_total,
        RP.write_io_stall_total_ms,
        RP.write_io_stall_queued_ms,
        RP.io_issue_violations_total,
        RP.io_issue_delay_total_ms,
        RP.io_issue_delay_non_throttled_total_ms,
        RP.total_cpu_delayed_ms,
        RP.total_cpu_active_ms,
        RP.total_cpu_violation_delay_ms,
        RP.total_cpu_violation_sec,
        RP.total_cpu_usage_preemptive_ms
FROM dbo.ResourceGovernorResourcePools RP
LEFT JOIN Metrics M ON RP.ResourcePoolID = M.ResourcePoolID
WHERE RP.InstanceID = @InstanceID