CREATE PROC dbo.XETraceSession_Complete(
    @XETraceSessionID BIGINT,
    @Status TINYINT, /* 1 Completed, 2 Cancelled, 3 Error */
    @TargetType TINYINT = NULL, /* resolved target echoed back by the service (1 event_file, 2 ring_buffer) */
    @GeneratedDDL NVARCHAR(MAX) = NULL, /* service-generated DDL echoed back for audit */
    @XelData VARBINARY(MAX) = NULL,
    @ErrorMessage NVARCHAR(MAX) = NULL
)
AS
SET NOCOUNT ON
/* Setting Status away from 0 (Running) releases the one-running-per-instance unique index.  TargetType and
   GeneratedDDL are resolved/generated by the service and only known now, so they're written on completion.
   COALESCE keeps any existing value if the caller doesn't supply one. */
/* Only transition a Running (0) trace to terminal.  If it was already terminated (e.g. force-cancelled via
   XETraceSession_CancelRunning during a cleanup), a late completion must not overwrite that status. */
UPDATE dbo.XETraceSession
    SET Status = @Status,
        EndTime = SYSUTCDATETIME(),
        TargetType = COALESCE(@TargetType, TargetType),
        GeneratedDDL = COALESCE(@GeneratedDDL, GeneratedDDL),
        XelData = COALESCE(@XelData, XelData),
        ErrorMessage = COALESCE(@ErrorMessage, ErrorMessage)
WHERE XETraceSessionID = @XETraceSessionID
AND Status = 0
