CREATE TABLE Alert.ActiveAlerts(
	AlertID BIGINT IDENTITY(1,1) NOT NULL,
	InstanceID INT NOT NULL,
	Priority TINYINT NOT NULL,
	AlertType VARCHAR(50) NOT NULL,
	AlertKey NVARCHAR(128) NOT NULL,
	FirstMessage NVARCHAR(MAX) NOT NULL,
	LastMessage NVARCHAR(MAX) NOT NULL,
	TriggerDate DATETIME2 NOT NULL CONSTRAINT DF_Aler_ActiveAlerts_TriggerDate DEFAULT(SYSUTCDATETIME()),
	UpdatedDate DATETIME2 NOT NULL CONSTRAINT DF_Alert_ActiveAlerts_UpdatedDate DEFAULT(SYSUTCDATETIME()),
	FirstNotification DATETIME2 NULL,
	LastNotification DATETIME2 NULL,
	UpdateCount INT NOT NULL CONSTRAINT DF_Alert_ActiveAlerts_UpdateCount DEFAULT(0),
	ResolvedCount INT NOT NULL CONSTRAINT DF_Alert_ActiveAlerts_ResolvedCount DEFAULT(0),
	NotificationCount INT NOT NULL CONSTRAINT DF_Alert_ActiveAlerts_NotificationCount DEFAULT(0),
	FailedNotificationCount INT NOT NULL CONSTRAINT DF_Alert_ActiveAlerts_FailedNotificationCount DEFAULT(0),
	IsAcknowledged BIT NOT NULL CONSTRAINT DF_Alert_ActiveAlerts_IsAcknowledged DEFAULT(0),
	IsResolved BIT NOT NULL CONSTRAINT DF_Alert_ActiveAlerts_IsRevolved DEFAULT(0),
	ResolvedDate DATETIME2 NULL,
	IsBlackout BIT NOT NULL CONSTRAINT DF_Alert_ActiveAlerts_IsBlackout DEFAULT(0),
	Escalated DATETIME2 NULL,
	DeEscalated DATETIME2 NULL,
	Notes NVARCHAR(MAX) NULL,
	RuleID INT NULL,
	AcknowledgedDate DATETIME2 NULL,
	CONSTRAINT FK_ActiveAlerts_Instances FOREIGN KEY(InstanceID) REFERENCES dbo.Instances(InstanceID),
	CONSTRAINT FK_ActiveAlerts_Rules FOREIGN KEY(RuleID) REFERENCES Alert.Rules(RuleID),
	CONSTRAINT PK_ActiveAlerts PRIMARY KEY(AlertID),
	CONSTRAINT CK_ActiveAlerts_Priority CHECK(Priority BETWEEN 0 AND 41),
)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_ActiveAlerts_InstanceID_AlertKey ON Alert.ActiveAlerts(InstanceID,AlertKey)
