CREATE FUNCTION dbo.DatabaseSettingsUnpivot_Get(@InstanceID INT)
RETURNS TABLE
AS
RETURN
SELECT  d.DatabaseID,
        u.Setting,
        u.Value,
        d.is_in_standby
FROM dbo.Databases d WITH(FORCESEEK)
CROSS APPLY (VALUES
    ('owner_sid', CAST(d.owner_sid AS SQL_VARIANT)),
    ('compatibility_level', CAST(d.compatibility_level AS SQL_VARIANT)),
    ('collation_name', CAST(d.collation_name AS SQL_VARIANT)),
    ('user_access', CAST(d.user_access AS SQL_VARIANT)),
    ('is_read_only', CAST(d.is_read_only AS SQL_VARIANT)),
    ('is_auto_close_on', CAST(d.is_auto_close_on AS SQL_VARIANT)),
    ('is_auto_shrink_on', CAST(d.is_auto_shrink_on AS SQL_VARIANT)),
    ('state', CAST(d.state AS SQL_VARIANT)),
    ('is_cleanly_shutdown', CAST(d.is_cleanly_shutdown AS SQL_VARIANT)),
    ('is_supplemental_logging_enabled', CAST(d.is_supplemental_logging_enabled AS SQL_VARIANT)),
    ('snapshot_isolation_state', CAST(d.snapshot_isolation_state AS SQL_VARIANT)),
    ('is_read_committed_snapshot_on', CAST(d.is_read_committed_snapshot_on AS SQL_VARIANT)),
    ('recovery_model', CAST(d.recovery_model AS SQL_VARIANT)),
    ('page_verify_option', CAST(d.page_verify_option AS SQL_VARIANT)),
    ('is_auto_create_stats_on', CAST(d.is_auto_create_stats_on AS SQL_VARIANT)),
    ('is_auto_create_stats_incremental_on', CAST(d.is_auto_create_stats_incremental_on AS SQL_VARIANT)),
    ('is_auto_update_stats_on', CAST(d.is_auto_update_stats_on AS SQL_VARIANT)),
    ('is_auto_update_stats_async_on', CAST(d.is_auto_update_stats_async_on AS SQL_VARIANT)),
    ('is_ansi_null_default_on', CAST(d.is_ansi_null_default_on AS SQL_VARIANT)),
    ('is_ansi_nulls_on', CAST(d.is_ansi_nulls_on AS SQL_VARIANT)),
    ('is_ansi_padding_on', CAST(d.is_ansi_padding_on AS SQL_VARIANT)),
    ('is_ansi_warnings_on', CAST(d.is_ansi_warnings_on AS SQL_VARIANT)),
    ('is_arithabort_on', CAST(d.is_arithabort_on AS SQL_VARIANT)),
    ('is_concat_null_yields_null_on', CAST(d.is_concat_null_yields_null_on AS SQL_VARIANT)),
    ('is_numeric_roundabort_on', CAST(d.is_numeric_roundabort_on AS SQL_VARIANT)),
    ('is_quoted_identifier_on', CAST(d.is_quoted_identifier_on AS SQL_VARIANT)),
    ('is_recursive_triggers_on', CAST(d.is_recursive_triggers_on AS SQL_VARIANT)),
    ('is_cursor_close_on_commit_on', CAST(d.is_cursor_close_on_commit_on AS SQL_VARIANT)),
    ('is_local_cursor_default', CAST(d.is_local_cursor_default AS SQL_VARIANT)),
    ('is_fulltext_enabled', CAST(d.is_fulltext_enabled AS SQL_VARIANT)),
    ('is_trustworthy_on', CAST(d.is_trustworthy_on AS SQL_VARIANT)),
    ('is_db_chaining_on', CAST(d.is_db_chaining_on AS SQL_VARIANT)),
    ('is_parameterization_forced', CAST(d.is_parameterization_forced AS SQL_VARIANT)),
    ('is_master_key_encrypted_by_server', CAST(d.is_master_key_encrypted_by_server AS SQL_VARIANT)),
    ('is_query_store_on', CAST(d.is_query_store_on AS SQL_VARIANT)),
    ('is_published', CAST(d.is_published AS SQL_VARIANT)),
    ('is_subscribed', CAST(d.is_subscribed AS SQL_VARIANT)),
    ('is_merge_published', CAST(d.is_merge_published AS SQL_VARIANT)),
    ('is_distributor', CAST(d.is_distributor AS SQL_VARIANT)),
    ('is_sync_with_backup', CAST(d.is_sync_with_backup AS SQL_VARIANT)),
    ('is_broker_enabled', CAST(d.is_broker_enabled AS SQL_VARIANT)),
    ('is_date_correlation_on', CAST(d.is_date_correlation_on AS SQL_VARIANT)),
    ('is_cdc_enabled', CAST(d.is_cdc_enabled AS SQL_VARIANT)),
    ('is_encrypted', CAST(d.is_encrypted AS SQL_VARIANT)),
    ('is_honor_broker_priority_on', CAST(d.is_honor_broker_priority_on AS SQL_VARIANT)),
    ('replica_id', CAST(d.replica_id AS SQL_VARIANT)),
    ('group_database_id', CAST(d.group_database_id AS SQL_VARIANT)),
    ('resource_pool_id', CAST(d.resource_pool_id AS SQL_VARIANT)),
    ('default_language_lcid', CAST(d.default_language_lcid AS SQL_VARIANT)),
    ('default_language_name', CAST(d.default_language_name AS SQL_VARIANT)),
    ('default_fulltext_language_lcid', CAST(d.default_fulltext_language_lcid AS SQL_VARIANT)),
    ('default_fulltext_language_name', CAST(d.default_fulltext_language_name AS SQL_VARIANT)),
    ('is_nested_triggers_on', CAST(d.is_nested_triggers_on AS SQL_VARIANT)),
    ('is_transform_noise_words_on', CAST(d.is_transform_noise_words_on AS SQL_VARIANT)),
    ('two_digit_year_cutoff', CAST(d.two_digit_year_cutoff AS SQL_VARIANT)),
    ('containment', CAST(d.containment AS SQL_VARIANT)),
    ('target_recovery_time_in_seconds', CAST(d.target_recovery_time_in_seconds AS SQL_VARIANT)),
    ('delayed_durability', CAST(d.delayed_durability AS SQL_VARIANT)),
    ('is_memory_optimized_elevate_to_snapshot_on', CAST(d.is_memory_optimized_elevate_to_snapshot_on AS SQL_VARIANT)),
    ('is_federation_member', CAST(d.is_federation_member AS SQL_VARIANT)),
    ('is_remote_data_archive_enabled', CAST(d.is_remote_data_archive_enabled AS SQL_VARIANT)),
    ('is_mixed_page_allocation_on', CAST(d.is_mixed_page_allocation_on AS SQL_VARIANT)),
    ('is_ledger_on', CAST(d.is_ledger_on AS SQL_VARIANT)),
    ('catalog_collation_type', CAST(d.catalog_collation_type AS SQL_VARIANT)),
    ('is_accelerated_database_recovery_on', CAST(d.is_accelerated_database_recovery_on AS SQL_VARIANT)),
    ('is_change_feed_enabled', CAST(d.is_change_feed_enabled AS SQL_VARIANT)),
    ('is_event_stream_enabled', CAST(d.is_event_stream_enabled AS SQL_VARIANT)),
    ('is_memory_optimized_enabled', CAST(d.is_memory_optimized_enabled AS SQL_VARIANT)),
    ('is_temporal_history_retention_enabled', CAST(d.is_temporal_history_retention_enabled AS SQL_VARIANT)),
    ('is_optimized_locking_on', CAST(d.is_optimized_locking_on AS SQL_VARIANT))
) u(Setting, Value)
WHERE d.InstanceID = @InstanceID
AND u.Value IS NOT NULL 