CREATE FUNCTION dbo.DateGroupingMins(@DateTime DATETIME,@Mins INT)
RETURNS TABLE
AS
RETURN
SELECT CASE WHEN @Mins = 0 THEN @DateTime ELSE DATEADD(MINUTE, (DATEDIFF(MINUTE, 0, @DateTime) / @Mins) * @Mins, 0) END AS DateGroup