//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAChecks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBAChecks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @ProcessorNameString NVARCHAR(512)
        ///DECLARE @SystemManufacturer NVARCHAR(512)
        ///DECLARE @SystemProductName NVARCHAR(512)
        ///DECLARE @PVDriver NVARCHAR(512)
        ///DECLARE @IsAgentRunning BIT
        ///DECLARE @InstantFileInitializationEnabled BIT
        ///IF EXISTS(SELECT * FROM fn_my_permissions ( &apos;sys.xp_instance_regread&apos;, &apos;OBJECT&apos; ) WHERE permission_name=&apos;EXECUTE&apos;)
        ///BEGIN  
        ///	EXEC sys.xp_instance_regread N&apos;HKEY_LOCAL_MACHINE&apos;, N&apos;HARDWARE\DESCRIPTION\System\CentralProcessor\0&apos;, N&apos;ProcessorNameString&apos;,@ProcessorNameString O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistryProperties {
            get {
                return ResourceManager.GetString("RegistryProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH T AS (
        ///SELECT j.job_id,j.name,
        ///MAX(CASE WHEN jh.step_id=0 AND jh.run_status &lt;&gt; 1 THEN dt.RunDateTime ELSE NULL END) LastFail,
        ///MAX(CASE WHEN jh.step_id=0 AND jh.run_status = 1 THEN dt.RunDateTime ELSE NULL END) LastSucceed,
        ///SUM(CASE WHEN jh.step_id=0 AND jh.run_status &lt;&gt; 1 AND dt.RunDateTime&gt;=DATEADD(hh,-24,GETDATE()) THEN 1 ELSE 0 END) FailCount24Hrs,
        ///SUM(CASE WHEN jh.step_id=0 AND jh.run_status = 1 AND dt.RunDateTime&gt;=DATEADD(hh,-24,GETDATE()) THEN 1 ELSE 0 END) SucceedCount24Hrs,
        ///SUM(CASE WHEN  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLAgentJobSummary {
            get {
                return ResourceManager.GetString("SQLAgentJobSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select database_name,type, MAX(backup_start_date) LastBackup
        ///from msdb.dbo.backupset
        ///where server_name=@@SERVERNAME
        ///AND backup_finish_date&gt;=DATEADD(d,-10,GETUTCDATE())
        ///group by database_name, type.
        /// </summary>
        internal static string SQLBackups {
            get {
                return ResourceManager.GetString("SQLBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT configuration_id,CAST(value as BIGINT) as value,CAST(value_in_use as BIGINT) as value_in_use
        ///FROM sys.configurations.
        /// </summary>
        internal static string SQLConfigurations {
            get {
                return ResourceManager.GetString("SQLConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT name,
        ///       database_id,
        ///       source_database_id,
        ///       --owner_sid,
        ///	   CASE WHEN owner_sid=0x01 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS IsOwnerSA,
        ///       create_date,
        ///       compatibility_level,
        ///       collation_name,
        ///       user_access,
        ///       --user_access_desc,
        ///       is_read_only,
        ///       is_auto_close_on,
        ///       is_auto_shrink_on,
        ///       state,
        ///       --state_desc,
        ///       is_in_standby,
        ///       is_cleanly_shutdown,
        ///       is_supplemental_logging_enabled,
        ///       snaps [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLDatabases {
            get {
                return ResourceManager.GetString("SQLDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT dovs.volume_mount_point AS Name,
        ///	dovs.total_bytes as Capacity,
        ///	dovs.available_bytes as FreeSpace,
        ///	dovs.logical_volume_name as Label
        ///FROM sys.master_files mf
        ///CROSS APPLY sys.dm_os_volume_stats(mf.database_id, mf.FILE_ID) dovs.
        /// </summary>
        internal static string SQLDrives {
            get {
                return ResourceManager.GetString("SQLDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @DBName SYSNAME
        ///DECLARE @SQL NVARCHAR(MAX)
        ///CREATE TABLE #FileList ( 
        ///database_id INT,
        ///file_id INT,
        ///data_space_id INT,
        ///name SYSNAME,
        ///filegroup_name SYSNAME,
        ///physical_name nvarchar(260),
        ///type TINYINT,
        ///size bigint,
        ///space_used bigint,
        ///max_size bigint,
        ///growth bigint,
        ///is_percent_growth bit,
        ///is_read_only bit
        ///)
        ///
        ///DECLARE DBs CURSOR FOR
        ///SELECT name
        ///FROM sys.databases
        ///WHERE state  = 0
        ///AND DATABASEPROPERTYEX(name, &apos;Updateability&apos;) = &apos;READ_WRITE&apos;
        ///
        ///OPEN DBs
        ///FETCH NEXT FROM DBs INTO @DBNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLFiles {
            get {
                return ResourceManager.GetString("SQLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH t
        ///AS (SELECT rsh.destination_database_name AS database_name,
        ///           rsh.restore_date,
        ///           bs.backup_start_date,
        ///           bmf.physical_device_name AS last_file,
        ///           ROW_NUMBER() OVER (PARTITION BY rsh.destination_database_name
        ///                              ORDER BY rsh.restore_date DESC
        ///                             ) rnum
        ///    FROM msdb.dbo.restorehistory rsh
        ///        INNER JOIN msdb.dbo.backupset bs ON rsh.backup_set_id = bs.backup_set_id
        ///        INNER JOIN msdb.dbo.restoref [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLLogShipping {
            get {
                return ResourceManager.GetString("SQLLogShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CAST(SERVERPROPERTY(&apos;BuildClrVersion&apos;) as nvarchar(128)) as BuildClrVersion ,
        ///CAST(SERVERPROPERTY(&apos;Collation&apos;) as nvarchar(128)) as Collation ,
        ///CAST(SERVERPROPERTY(&apos;CollationID&apos;) as int) as CollationID ,
        ///CAST(SERVERPROPERTY(&apos;ComparisonStyle&apos;) as int) as ComparisonStyle ,
        ///CAST(SERVERPROPERTY(&apos;ComputerNamePhysicalNetBIOS&apos;) as nvarchar(128)) as ComputerNamePhysicalNetBIOS ,
        ///CAST(SERVERPROPERTY(&apos;Edition&apos;) as nvarchar(128)) as Edition ,
        ///CAST(SERVERPROPERTY(&apos;EditionID&apos;) as bigint) as EditionID ,
        ///CAS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLProperties {
            get {
                return ResourceManager.GetString("SQLProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH T AS (
        ///SELECT &apos;BuildClrVersion&apos; as Property
        ///UNION ALL 
        ///SELECT &apos;Collation&apos;
        ///UNION ALL 
        ///SELECT &apos;CollationID&apos;
        ///UNION ALL 
        ///SELECT &apos;ComparisonStyle&apos;
        ///UNION ALL 
        ///SELECT &apos;ComputerNamePhysicalNetBIOS&apos;
        ///UNION ALL 
        ///SELECT &apos;Edition&apos;
        ///UNION ALL 
        ///SELECT &apos;EditionID&apos;
        ///UNION ALL 
        ///SELECT &apos;EngineEdition&apos;
        ///UNION ALL 
        ///SELECT &apos;HadrManagerStatus&apos;
        ///UNION ALL 
        ///SELECT &apos;InstanceDefaultDataPath&apos;
        ///UNION ALL 
        ///SELECT &apos;InstanceDefaultLogPath&apos;
        ///UNION ALL 
        ///SELECT &apos;InstanceName&apos;
        ///UNION ALL 
        ///SELECT &apos;IsAdvancedAnalyticsInst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLPropertiesOLD {
            get {
                return ResourceManager.GetString("SQLPropertiesOLD", resourceCulture);
            }
        }
    }
}
