CREATE TABLE [dbo].[DatabaseMirroring] (
    [DatabaseID]                   INT              NOT NULL,
    [InstanceID]                   INT              NOT NULL,
    [mirroring_guid]               UNIQUEIDENTIFIER NULL,
    [mirroring_state]              TINYINT          NULL,
    [mirroring_state_desc]         AS               (case [mirroring_state] when (0) then 'SUSPENDED' when (1) then 'DISCONNECTED' when (2) then 'SYNCHRONIZING' when (3) then 'PENDING_FAILOVER' when (4) then 'SYNCHRONIZED' when (5) then 'UNSYNCHRONIZED' when (6) then 'SYNCHRONIZED'  end),
    [mirroring_role]               TINYINT          NULL,
    [mirroring_role_desc]          AS               (case [mirroring_role] when (1) then 'PRINCIPAL' when (2) then 'MIRROR'  end),
    [mirroring_role_sequence]      INT              NULL,
    [mirroring_safety_level]       TINYINT          NULL,
    [mirroring_safety_level_desc]  AS               (case [mirroring_safety_level] when (0) then 'UNKNOWN' when (1) then 'OFF' when (2) then 'FULL'  end),
    [mirroring_safety_sequence]    INT              NULL,
    [mirroring_partner_name]       NVARCHAR (128)   NULL,
    [mirroring_partner_instance]   NVARCHAR (128)   NULL,
    [mirroring_witness_name]       NVARCHAR (128)   NULL,
    [mirroring_witness_state]      TINYINT          NULL,
    [mirroring_witness_state_desc] AS               (case [mirroring_witness_state] when (0) then 'UNKNOWN' when (1) then 'CONNECTED' when (2) then 'DISCONNECTED'  end),
    [mirroring_failover_lsn]       DECIMAL (25)     NULL,
    [mirroring_connection_timeout] INT              NULL,
    [mirroring_redo_queue]         INT              NULL,
    [mirroring_redo_queue_type]    NVARCHAR (60)    NULL,
    [mirroring_end_of_log_lsn]     DECIMAL (25)     NULL,
    [mirroring_replication_lsn]    DECIMAL (25)     NULL,
    CONSTRAINT [PK_DatabaseMirroring] PRIMARY KEY CLUSTERED ([InstanceID] ASC, [DatabaseID] ASC),
    CONSTRAINT [FK_DatabaseMirroring_Databases] FOREIGN KEY ([DatabaseID]) REFERENCES [dbo].[Databases] ([DatabaseID]),
    CONSTRAINT [FK_DatabaseMirroring_Instances] FOREIGN KEY ([InstanceID]) REFERENCES [dbo].[Instances] ([InstanceID]),
    CONSTRAINT [UX_DatabaseMirroring] UNIQUE NONCLUSTERED ([DatabaseID] ASC)
);
