CREATE TABLE dbo.DBADashAgent(
	DBADashAgentID INT IDENTITY(1,1) NOT NULL,
	AgentHostName NVARCHAR(16) NOT NULL,
	AgentServiceName NVARCHAR(256) NOT NULL,
	AgentVersion VARCHAR(30) NOT NULL,
	AgentPath NVARCHAR(260) NOT NULL,
	CONSTRAINT PK_DBADashAgent PRIMARY KEY(DBADashAgentID),
	INDEX IX_DBADashAgent UNIQUE NONCLUSTERED (AgentHostName,AgentServiceName)
)