CREATE TABLE dbo.Jobs (
    InstanceID INT NOT NULL,
    job_id UNIQUEIDENTIFIER NOT NULL,
    originating_server NVARCHAR(128) NULL,
    name NVARCHAR(128) NULL,
    enabled TINYINT NULL,
    description NVARCHAR(512) NULL,
    start_step_id INT NULL,
    category_id INT NULL,
    category NVARCHAR(128) NULL,
    owner NVARCHAR(128) NULL,
    notify_level_eventlog INT NULL,
    notify_level_email INT NULL,
    notify_level_netsend INT NULL,
    notify_level_page INT NULL,
    notify_email_operator NVARCHAR(128) NULL,
    notify_netsend_operator NVARCHAR(128) NULL,
    notify_page_operator NVARCHAR(128) NULL,
    delete_level INT NULL,
    date_created DATETIME NULL,
    date_modified DATETIME NULL,
    version_number INT NULL,
    has_schedule BIT NULL,
    has_server BIT NULL,
    has_step BIT NULL,
    DDLID BIGINT NULL,
    IsActive BIT NOT NULL,
    SnapshotCreatedDate DATETIME2(2) NULL,
    SnapshotUpdatedDate DATETIME2(2) NULL,
    LastSucceeded DATETIME2(2) NULL,
    LastFailed DATETIME2(2) NULL,
    AckDate DATETIME2(2) NULL,
    StepLastFailed DATETIME2(2) NULL,
    CONSTRAINT PK_Jobs PRIMARY KEY CLUSTERED (InstanceID ASC, job_id ASC),
    CONSTRAINT FK_Jobs_DDL FOREIGN KEY (DDLID) REFERENCES dbo.DDL (DDLID),
    CONSTRAINT FK_Jobs_Instances FOREIGN KEY (InstanceID) REFERENCES dbo.Instances (InstanceID)
);

GO
CREATE NONCLUSTERED INDEX IX_Jobs_DDLID ON dbo.Jobs (DDLID);