CREATE TABLE dbo.ResourceGovernorResourcePoolsMetrics (
	ResourcePoolID INT NOT NULL,
	InstanceID INT NOT NULL,
	SnapshotDate DATETIME2(7) NOT NULL,
	PeriodTimeMs BIGINT NOT NULL,
	diff_cpu_usage_ms BIGINT NOT NULL,
	diff_memgrant_count BIGINT NOT NULL,
	diff_memgrant_timeout_count BIGINT NOT NULL,
	diff_out_of_memory_count BIGINT NOT NULL,
	diff_read_io_queued INT NULL,
	diff_read_io_issued INT NULL,
	diff_read_io_completed INT NOT NULL,
	diff_read_io_throttled INT NULL,
	diff_read_bytes BIGINT NOT NULL,
	diff_read_io_stall_ms BIGINT NOT NULL,
	diff_read_io_stall_queued_ms BIGINT NULL,
	diff_write_io_queued INT NULL,
	diff_write_io_issued INT NULL,
	diff_write_io_completed INT NOT NULL,
	diff_write_io_throttled INT NULL,
	diff_write_bytes BIGINT NOT NULL,
	diff_write_io_stall_ms BIGINT NOT NULL,
	diff_write_io_stall_queued_ms BIGINT NULL,
	diff_io_issue_violations INT NULL,
	diff_io_issue_delay_ms BIGINT NULL,
	diff_io_issue_delay_non_throttled_ms BIGINT NULL,
	diff_cpu_delayed_ms BIGINT NOT NULL,
	diff_cpu_active_ms BIGINT NOT NULL,
	diff_cpu_violation_delay_ms BIGINT NOT NULL,
	diff_cpu_violation_sec BIGINT NOT NULL,
	diff_cpu_usage_preemptive_ms BIGINT NOT NULL,
	cache_memory_kb BIGINT NOT NULL,
	compile_memory_kb BIGINT NOT NULL,
	used_memgrant_kb BIGINT NOT NULL,	
	active_memgrant_count INT NOT NULL,
	active_memgrant_kb BIGINT NOT NULL,
	memgrant_waiter_count INT NOT NULL,
	max_memory_kb BIGINT NOT NULL,
	used_memory_kb BIGINT NOT NULL,
	target_memory_kb BIGINT NOT NULL,
	cpu_count INT NULL,
	max_cpu_percent INT NULL,
	cap_cpu_percent INT NULL,
    CONSTRAINT PK_ResourceGovernorResourcePoolsMetrics PRIMARY KEY CLUSTERED (InstanceID, SnapshotDate, ResourcePoolID) WITH(DATA_COMPRESSION=PAGE) ON PS_ResourceGovernorResourcePoolsMetrics(SnapshotDate)
)
