CREATE TABLE dbo.ResourceGovernorWorkloadGroupsMetrics(
	InstanceID INT NOT NULL,
	WorkloadGroupID INT NOT NULL,
	SnapshotDate DATETIME2(7) NOT NULL,
	PeriodTimeMs BIGINT NOT NULL,
	diff_request_count BIGINT NOT NULL,
	diff_queued_request_count BIGINT NOT NULL,
	diff_cpu_limit_violation_count BIGINT NOT NULL,
	diff_cpu_usage_ms BIGINT NOT NULL,
	diff_lock_wait_count BIGINT NOT NULL,
	diff_lock_wait_time_ms BIGINT NOT NULL,
	diff_query_optimization_count BIGINT NOT NULL,
	diff_suboptimal_plan_generation_count BIGINT NOT NULL,
	diff_reduced_memgrant_count BIGINT NOT NULL,
	diff_cpu_usage_preemptive_ms BIGINT NULL,
	diff_tempdb_data_limit_violation_count BIGINT NULL,
	active_request_count INT NOT NULL,
	queued_request_count INT NOT NULL,
	blocked_task_count INT NOT NULL,
	active_parallel_thread_count BIGINT NOT NULL,
	tempdb_data_space_kb BIGINT NULL,
	cpu_count INT NULL,
	CONSTRAINT PK_ResourceGovernorWorkloadGroupsMetrics PRIMARY KEY CLUSTERED (InstanceID, SnapshotDate, WorkloadGroupID) WITH(DATA_COMPRESSION=PAGE) ON PS_ResourceGovernorWorkloadGroupsMetrics(SnapshotDate)
);