CREATE TABLE dbo.Summary (
    InstanceID INT NOT NULL ,
    Instance NVARCHAR(128) NOT NULL,
    InstanceGroupName NVARCHAR(128) NOT NULL,
    LogShippingStatus INT NOT NULL,
    FullBackupStatus INT NOT NULL,
    LogBackupStatus INT NOT NULL,
    DiffBackupStatus INT NOT NULL,
    DriveStatus INT NOT NULL,
    FileFreeSpaceStatus INT NOT NULL,
    LogFreeSpaceStatus INT NOT NULL,
    JobStatus INT NOT NULL,
    AGStatus INT NOT NULL,
    DetectedCorruptionDateUtc DATETIME2(3) NULL,
    CorruptionStatus INT NOT NULL,
    CollectionErrorStatus INT NOT NULL,
    CollectionErrorCount INT NOT NULL,
    SnapshotAgeMin INT NULL,
    SnapshotAgeMax INT NULL,
    SnapshotAgeStatus INT NOT NULL,
    sqlserver_start_time_utc DATETIME NULL,
    UTCOffset INT NULL,
    sqlserver_uptime INT NULL,
    UptimeStatus INT NOT NULL,
    UptimeWarningThreshold INT NULL,
    UptimeCriticalThreshold INT NULL,
    UptimeConfiguredLevel VARCHAR(8) NULL,
    AdditionalUptime INT NULL,
    host_uptime BIGINT NULL,
    host_start_time_utc DATETIME2(2) NULL,
    MemoryDumpCount INT NULL,
    LastMemoryDump DATETIME NULL,
    LastMemoryDumpUTC DATETIME NULL,
    MemoryDumpStatus INT NOT NULL,
    LastGoodCheckDBStatus INT NOT NULL,
    LastGoodCheckDBCriticalCount INT NULL,
    LastGoodCheckDBWarningCount INT NULL,
    LastGoodCheckDBHealthyCount INT NULL,
    LastGoodCheckDBNACount INT NULL,
    OldestLastGoodCheckDBTime DATETIME2(3) NULL,
    DaysSinceLastGoodCheckDB INT NULL,
    LastAlert DATETIME2(3) NULL,
    LastCritical DATETIME2(3) NULL,
    TotalAlerts INT NULL,
    AlertStatus INT NULL,
    AlertSnapshotDate DATETIME2(2) NULL,
    IsAgentRunning BIT NULL,
    IsAgentRunningStatus INT NOT NULL,
    CustomCheckStatus TINYINT NOT NULL,
    MirroringStatus INT NOT NULL,
    ElasticPoolStorageStatus INT NOT NULL,
    PctMaxSizeStatus INT NOT NULL,
    QueryStoreStatus INT NOT NULL,
    DBMailStatus INT NOT NULL,
    DBMailStatusDescription NVARCHAR(500) NULL,
    IdentityStatus INT NOT NULL,
    MaxIdentityPctUsed DECIMAL(38, 6) NULL,
    ShowInSummary BIT NOT NULL,
    IsHidden BIT NOT NULL,
    DatabaseStateStatus INT NOT NULL,
	RefreshDate DATETIME NOT NULL,
	IsAzure BIT NOT NULL,
	CONSTRAINT PK_Summary PRIMARY KEY(InstanceID)
);
