CREATE TABLE dbo.XETraceSession(
    XETraceSessionID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_XETraceSession PRIMARY KEY,
    InstanceID INT NOT NULL,
    MessageGroupID UNIQUEIDENTIFIER NOT NULL, /* = the message Id, used to correlate a cancellation request */
    RequestedBy NVARCHAR(256) NOT NULL,
    EventTypes VARCHAR(200) NOT NULL,
    FiltersJson NVARCHAR(MAX) NULL, /* serialized typed filter model - audit only */
    GeneratedDDL NVARCHAR(MAX) NULL, /* exact CREATE EVENT SESSION generated by the service (echoed back, set on completion) - audit only */
    TargetType TINYINT NULL, /* 1 = event_file, 2 = ring_buffer - resolved by the service, set on completion */
    MaxDurationSeconds INT NOT NULL,
    Status TINYINT NOT NULL CONSTRAINT DF_XETraceSession_Status DEFAULT(0), /* 0 Running, 1 Completed, 2 Cancelled, 3 Error */
    TotalEvents INT NOT NULL CONSTRAINT DF_XETraceSession_TotalEvents DEFAULT(0),
    XelData VARBINARY(MAX) NULL, /* captured .xel bytes (event_file, best-effort) */
    StartTime DATETIME2(3) NOT NULL CONSTRAINT DF_XETraceSession_StartTime DEFAULT(SYSUTCDATETIME()),
    EndTime DATETIME2(3) NULL,
    ErrorMessage NVARCHAR(MAX) NULL,
    CONSTRAINT FK_XETraceSession_Instances FOREIGN KEY (InstanceID) REFERENCES dbo.Instances (InstanceID)
);
GO
/* Enforce one running (Status = 0) trace per instance.  Second guard behind the source-instance session check. */
CREATE UNIQUE INDEX UQ_XETraceSession_OneRunningPerInstance
    ON dbo.XETraceSession(InstanceID) WHERE Status = 0;
GO
CREATE NONCLUSTERED INDEX IX_XETraceSession_InstanceID_StartTime
    ON dbo.XETraceSession(InstanceID, StartTime DESC)
GO
