CREATE TABLE dbo.XETraceSession(
    XETraceSessionID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_XETraceSession PRIMARY KEY,
    InstanceID INT NOT NULL,
    MessageGroupID UNIQUEIDENTIFIER NOT NULL, /* = the message Id, used to correlate a cancellation request */
    RunGroupID UNIQUEIDENTIFIER NULL, /* groups the N per-instance sessions of a single multi-instance (e.g. AG-wide) run so they reload together; NULL for a single-instance run */
    /* The login that started the trace, captured server-side (SUSER_SNAME(), see XETraceSession_Start) so it can't be
       forged by the caller.  Used both for display and as the owner the delete/history procs check to restrict a
       non-admin to their own traces.  The trace is always started on the user's own repository connection. */
    RequestedBy NVARCHAR(128) NOT NULL CONSTRAINT DF_XETraceSession_RequestedBy DEFAULT(SUSER_SNAME()),
    EventTypes VARCHAR(MAX) NOT NULL, /* comma-separated event names, audit/display only - MAX so a large selection is audited verbatim */
    FiltersJson NVARCHAR(MAX) NULL, /* serialized typed filter model - audit only */
    GeneratedDDL NVARCHAR(MAX) NULL, /* exact CREATE EVENT SESSION generated by the service (echoed back, set on completion) - audit only */
    TargetType TINYINT NULL, /* 1 = event_file, 2 = ring_buffer - resolved by the service, set on completion */
    MaxDurationSeconds INT NOT NULL,
    Status TINYINT NOT NULL CONSTRAINT DF_XETraceSession_Status DEFAULT(0), /* 0 Running, 1 Completed, 2 Cancelled, 3 Error */
    TotalEvents INT NOT NULL CONSTRAINT DF_XETraceSession_TotalEvents DEFAULT(0),
    XelData VARBINARY(MAX) NULL, /* captured .xel bytes (event_file, best-effort) */
    StartTime DATETIME2(3) NOT NULL CONSTRAINT DF_XETraceSession_StartTime DEFAULT(SYSUTCDATETIME()),
    EndTime DATETIME2(3) NULL,
    ErrorMessage NVARCHAR(MAX) NULL,
    /* Soft delete: deleting a trace removes the (bulk) captured event data + .xel but retains this session row for
       auditing.  The row is hidden from the reports/history and hard-deleted later by retention (dbo.PurgeXETrace). */
    DeletedDate DATETIME2(3) NULL,
    DeletedBy NVARCHAR(128) NULL,
    CONSTRAINT FK_XETraceSession_Instances FOREIGN KEY (InstanceID) REFERENCES dbo.Instances (InstanceID)
);
GO
/* Enforce one running (Status = 0) trace per instance.  Second guard behind the source-instance session check. */
CREATE UNIQUE INDEX UQ_XETraceSession_OneRunningPerInstance
    ON dbo.XETraceSession(InstanceID) WHERE Status = 0;
GO
CREATE NONCLUSTERED INDEX IX_XETraceSession_InstanceID_StartTime
    ON dbo.XETraceSession(InstanceID, StartTime DESC)
GO
/* Reload every per-instance session of a multi-instance run together (history grouping). */
CREATE NONCLUSTERED INDEX IX_XETraceSession_RunGroupID
    ON dbo.XETraceSession(RunGroupID) WHERE RunGroupID IS NOT NULL
GO
